### ISSUE TITLE
4 minutes long freezes on startup when connected to a Connectify access point

### ISSUE THREAD

**Issue by tuxayo** [syl20bnr/spacemacs.org#12]
All I know about the access point is that it's done with the same network
adapter to connect to the internet and make the hotspot. That might imply some
networking black magic and explain the following.
- When connected directly
  - when no packages to install, after launching Spacemacs, after few keystrokes
    (if I never stop typing during more than a second, it's fine...) it freezes.
    That freeze can't be Ctrl-C nor Ctrl-\, I have to `killall emacs` or wait 4
    minutes for the editor to be usable.
    - When using --insecure, Wireshark shoes that Emacs is trying to do HTTPS
      anyway (should be related to #5698 ) And I see that the TLS connections are
      to the gateway (private local address), that must be related to how
      Connectify makes it's hotspot and explain the different behavior when using
      the phone a an intermediary (because it adds a NAT that uses a similar IP addresses range)
  - Installing some packages will trigger this freeze after the timeout the install can continue and success!
- When connected using a phone as an intermediary (Android sharing by USB with a Linux PC)
  - when no packages to install, It's usable
  - can't install some packages, freeze during startup (when it tries to compile), that freeze can be
    Ctrl-C from the terminal that ran Emacs

All of this happens on a fresh install with a new .spacemacs

**Comment by TheBB** [comment]
Not website related.

**Comment by tuxayo** [comment]
Oh I'm sorry I ended up posting my draft. I copy pasted it to the right repo to finish it but I forgot to close this one and ended up posting it...
