### ISSUE TITLE
Bug with on hover CSS for code examples

### ISSUE THREAD

**Issue by sbdchd** [syl20bnr/spacemacs.org#14]
When hovering over the code example located [here](http://develop.spacemacs.org/doc/DOCUMENTATION#smooth-scrolling), the box displaying, "Emacs Lisp", is cut off at the top.

**Comment by nashamri** [comment]
@sbdchd thanks for reporting this. It's fixed now in the develop branch.

**Comment by syl20bnr** [comment]
Fixed :-)
