### ISSUE TITLE
Invalid TLS certificate

### ISSUE THREAD

**Issue by d12frosted** [syl20bnr/spacemacs.org#24]
Based on https://github.com/syl20bnr/spacemacs/issues/9244.

**Comment by d12frosted** [comment]
Who is Domain Registrar for spacemacs.org? 😸

**Comment by nashamri** [comment]
ummm, not sure :smiley_cat: 
ping @syl20bnr

**Comment by syl20bnr** [comment]
Phheew old issue, this is namecheap.

**Comment by hsribei** [comment]
Would be nice to have this resolved. Browsers are getting louder and louder in their warnings, and this must really scare away some new users and makes it harder for people to access documentation.

**Comment by candh** [comment]
Almost 2019 now and still not fixed.

**Comment by jwatt** [comment]
It looks like spacemacs.org is now hosted on github pages using the custom domain support. Here's the GitHub documentation on enabling HTTPS for that setup:

https://help.github.com/articles/securing-your-github-pages-site-with-https/

**Comment by fin-ger** [comment]
![image](https://user-images.githubusercontent.com/5300274/58636491-bd3a7e80-82f0-11e9-91ba-0f58612db01d.png)

1. Go into your project settings
2. enter `spacemacs.org` into the custom domain text field
3. Click Save

> Make sure to select the `gh-pages` branch for your project. I am using the master branch, but `spacemacs.org` doesn't!

Then wait a few minutes until the certificate is issued by let's encrypt. When this is finished you can select `Enforce HTTPS`.

When navigating to `spacemacs.org` you will automatically get redirected to `https://spacemacs.org`

**Comment by phoe** [comment]
Still not fixed at the end of 2019.

![Zrzut ekranu z 2019-11-04 18-14-57](https://user-images.githubusercontent.com/15045546/68142054-055c6d80-ff2f-11e9-9641-8fe2519eb8fa.png)

**Comment by syl20bnr** [comment]
Time to look at this 👼 Sorry for this silly long time and thank you for the pointers 💜

**Comment by syl20bnr** [comment]
Fixed!

<img width="291" alt="image" src="https://user-images.githubusercontent.com/1243537/68533651-5a1a3280-02f9-11ea-983a-d4b4914b533c.png">

Turns out that the DNS records was not properly set. I also changed the file `CNAME` to point to `www.spacemacs.org` to avoid conflicts with `develop.spacemacs.org` (at least I hope it will resolve the warnings I receive each time the websites change).
