### ISSUE TITLE
list of layer pages responding with 404 Not found

### ISSUE THREAD

**Issue by ghost** [syl20bnr/spacemacs.org#25]
helm
ivy
spacemacs
spacemacs-base
spacemacs-bootstrap
nlinum
spacemacs-completion
spacemacs-editing
spacemacs-editing-visual
spacemacs-evil
spacemacs-language
spacemacs-layouts
spacemacs-misc
spacemacs-org
spacemacs-ui
spacemacs-ui-visual

**Comment by nashamri** [comment]
hey @Ctaque thanks for this. The whole issue of 404 pages was solved in the develop branch http://develop.spacemacs.org. Although, most of the spacemacs-* layers have no documentation so far. Once someone provide documentation for those in the spacemacs repo, it will be merged automatically, thanks to @JAremko

**Comment by ghost** [comment]
I discovered the develop branch today and I saw it was fixed for some of the layers. I can maybe close this then, no need to stay open I think.
