### ISSUE TITLE
FAQ pronunciation guide is condescending

### ISSUE THREAD

**Issue by fishface60** [syl20bnr/spacemacs.org#26]
Spacemacs is an emacs distribution, so it is not unreasonable to assume that the pronunciation of emacs is included in the pronunciation of spacemacs, however the text is:

>   As it is written, that is space then macs.

I can understand not wanting to draw attention to the other interpretation of how it should be pronounced, "spac" being ableist slang after all, but as it is currently written it implies that the reader failed to read it correctly, when it is in fact ambiguous and the project has more to do with emacs than space.

Shortening it to just

>  Space then macs.

would be sufficient.

**Comment by syl20bnr** [comment]
:+1: 
Fixed with https://github.com/syl20bnr/spacemacs/commit/55ea4dfee634f6fddc736b14380767502cc5dc6d

Note that it will appear only on `https://develop.spacemacs.org` until we release the next stable version.
