### ISSUE TITLE
Contribute link goes 404

### ISSUE THREAD

**Issue by tuxayo** [syl20bnr/spacemacs.org#8]
In the links bellow the install and download buttons.

The "Contribute" link points to http://spacemacs.org/doc/CONTRIBUTE.html

**Comment by tuxayo** [comment]
Edit: fixed wrong link pasted into the description.

**Comment by nashamri** [comment]
Hey @tuxayo thanks for reporting this. There's already an open issue for this #6.

**Comment by tuxayo** [comment]
Ow, I looked to fast and managed to miss it, sorry.

(I also initially posted this comment in my other issue...)

**Comment by nashamri** [comment]
lol @tuxayo too much coffee?
